#!/bin/bash

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [[ -d "${ROOT}/graft-env" ]]
then
    ${ROOT}/graft-env/bin/python graft.py
else
    echo "graft-env not found - run 'make setup'"
fi
